sudo: false
language: node_js
node_js:
  - 10 # use nodejs v10 LTS
cache: yarn
branches:
  only:
    - gh-pages # build master branch only
script:
  - yarn install
  - yarn build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: master
  local-dir: public